Examen/Models/Clientes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Examen.Models
{
	public class Clientes
	{
		[Display(Name = "Codigo")]
		[Required(AllowEmptyStrings = false , ErrorMessage = "Ingrese el Codigo ")]
		[RegularExpression(@"^[\s]*(CLI[0-9]{3})$",ErrorMessage = "Formato CLI999")]
		public String codigo { get; set; }


		[Display(Name = "Razon Social")]
		[Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese La Razon Social ")]
		public String razonSocial { get; set; }

		[Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese la Fecha")]
		[DataType(DataType.Date)]
		[Display(Name = "Fecha de Inicio de Actividades")]
		public String fechaIA { get; set; }

		[Display(Name = "Pagina Web ( URL ) ")]
		[Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese la pagina web ")]
		[RegularExpression(@"^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$", ErrorMessage = "Ingresa una URL Valida")]
		public String paginaWeb { get; set; }



		[Display(Name = "Direccion")]
		[MaxLength(100)]
		public String direccion { get; set; }


		[Display(Name = "Rubro de Negocio")]
		[MaxLength(500)]
		public String rubro { get; set; }

	}
}

Examen/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Examen.Models;

namespace Examen.Controllers
{
    public class ClienteController : Controller
    {
		// Lista de Clientes
		static List<Clientes> Clientes = new List<Clientes>();
        // GET: Cliente
        public ActionResult Registro()
        {
            return View(new Clientes());
        }

		[HttpPost]public ActionResult Registro(Clientes reg)
		{
			if (ModelState.IsValid)
			{
				Clientes.Add(reg);
				return RedirectToAction("Listar");
			}
			else
			{
				ViewBag.mensaje = "Verifique los datos";
				return View(reg);
			}


		}

		public ActionResult Listar()
		{
			return View(Clientes);
		}
    }
}

Examen/Controllers/PlazaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Examen.Controllers
{
    public class PlazaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {

            return View();
        }
    }
}

Examen/Views/Cliente/Listar.cshtml
@model IEnumerable<Examen.Models.Clientes>

@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="content listar">
	<div class="listar-link">
		@Html.ActionLink("Nuevo Registro", "Registro", null, new { @class = "btn" })
	</div>

	<table class="table">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.codigo)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.razonSocial)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.fechaIA)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.paginaWeb)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.direccion)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.rubro)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.codigo)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.razonSocial)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.fechaIA)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.paginaWeb)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.direccion)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.rubro)
				</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
					@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
					@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
				</td>
			</tr>
		}

	</table>
</div>

Examen/Views/Cliente/Registro.cshtml
@model Examen.Models.Clientes

@{
    ViewBag.Title = "Registro";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


	<div class="content">
		@using (Html.BeginForm())
		{
		@Html.AntiForgeryToken()

		<div class="form-item">
			@Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label" })
			@Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.codigo, "")
		</div>


		<div class="form-item">
			@Html.LabelFor(model => model.razonSocial, htmlAttributes: new { @class = "control-label" })
			@Html.EditorFor(model => model.razonSocial, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.razonSocial, "")
		</div>

		<div class="form-item">
			@Html.LabelFor(model => model.fechaIA, htmlAttributes: new { @class = "control-label" })
			@Html.EditorFor(model => model.fechaIA, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.fechaIA, "")
		</div>

		<div class="form-item">
			@Html.LabelFor(model => model.paginaWeb, htmlAttributes: new { @class = "control-label" })
			@Html.EditorFor(model => model.paginaWeb, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.paginaWeb, "")
		</div>

		<div class="form-item">
			@Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label" })
			@Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.direccion, "")
		</div>

		<div class="form-item">
			@Html.LabelFor(model => model.rubro, htmlAttributes: new { @class = "control-label" })
			@Html.TextAreaFor(model => model.rubro, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.rubro, "")
		</div>

		<div class="form-item">
			<button type="submit" class="btn">Registrar</button>
		</div>
	}
	</div>


	<script>
		if ('@ViewBag.mensaje' != '')
			alert('@ViewBag.mensaje')
	</script>

Examen/Views/Plaza/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

	<div class="grid">
		<div class="grid-item grid-1">
			<div class="grid-image"><div class="grid-img grid-img-1"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-2">
			<div class="grid-image"><div class="grid-img grid-img-2"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-3">
			<div class="grid-image"><div class="grid-img grid-img-3"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-4">
			<div class="grid-image"><div class="grid-img grid-img-4"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-1">
			<div class="grid-image"><div class="grid-img grid-img-1"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-2">
			<div class="grid-image"><div class="grid-img grid-img-2"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-3">
			<div class="grid-image"><div class="grid-img grid-img-3"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-4">
			<div class="grid-image"><div class="grid-img grid-img-4"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-1">
			<div class="grid-image"><div class="grid-img grid-img-1"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-2">
			<div class="grid-image"><div class="grid-img grid-img-2"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-3">
			<div class="grid-image"><div class="grid-img grid-img-3"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-4">
			<div class="grid-image"><div class="grid-img grid-img-4"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-1">
			<div class="grid-image"><div class="grid-img grid-img-1"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-2">
			<div class="grid-image"><div class="grid-img grid-img-2"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-3">
			<div class="grid-image"><div class="grid-img grid-img-3"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-4">
			<div class="grid-image"><div class="grid-img grid-img-4"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-1">
			<div class="grid-image"><div class="grid-img grid-img-1"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-2">
			<div class="grid-image"><div class="grid-img grid-img-2"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-3">
			<div class="grid-image"><div class="grid-img grid-img-3"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-4">
			<div class="grid-image"><div class="grid-img grid-img-4"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-1">
			<div class="grid-image"><div class="grid-img grid-img-1"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-2">
			<div class="grid-image"><div class="grid-img grid-img-2"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-3">
			<div class="grid-image"><div class="grid-img grid-img-3"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-4">
			<div class="grid-image"><div class="grid-img grid-img-4"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-1">
			<div class="grid-image"><div class="grid-img grid-img-1"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-2">
			<div class="grid-image"><div class="grid-img grid-img-2"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-3">
			<div class="grid-image"><div class="grid-img grid-img-3"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="grid-item grid-4">
			<div class="grid-image"><div class="grid-img grid-img-4"></div></div>
			<div class="grid-btn"><i class="fas fa-ellipsis-h"></i></div>
		</div>
	</div>

Examen/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.2/css/bulma.min.css" rel="stylesheet"/>
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css")
</head>
<body>
	<div class="container">
		<header class="header">
			<div class="header-logo">
				<img src="~/img/logo.png" alt="logo de Zara" />
			</div>
			<div class="header-input">
				<input type="text" placeholder="Buscar" />
			</div>
			<nav class="nav">
				<ul class="nav-list">
					<li class="nav-item">
						@Html.ActionLink("Inicio", "Index", "Plaza", null, new { @class = "nav-link active" })
					</li>
					<li class="nav-item">
						@Html.ActionLink("Cliente", "Registro", "Cliente", null, new { @class = "nav-link" })
					</li>
				</ul>
			</nav>
		</header>
		<main class="main">
			@RenderBody()
		</main>
		<footer class="footer">
			<p>Todos los derechos reservados By
				<a class="footer-link" href="https://juliorivera.dev" target="_blank" rel="noreferrer noopener">Julio Cesar Rivera</a>
			&copy; 2020</p>
		</footer>
	</div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/js/all.min.js"></script>
</body>
</html>